---
kind: pipeline
type: docker
name: default

steps:
- name: build and push container
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    discord_token:
      from_secret: khg_bot_discord_token
    container_manager_pwd:
      from_secret: gitea_svc_container_manager
  commands:
    - apk add --no-cache make
    # - echo $container_manager_pwd | docker login -u svc-container-manager --password-stdin git.bhaanukaul.com
    - make build
    - make push

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

node:
  host: devastator
