---
kind: pipeline
name: default

steps:
- name: build and push container
  image: docker:dind
  settings:
    discord_token:
      from_secret: khg_bot_discord_token
    container_manager_pwd:
      from_secret: gitea_svc_container_manager
  commands:
    - echo $container_manager_pwd | docker login -u svc-container-manager --password-stdin git.bhaanukaul.com
    - make build
    - make push
