---
kind: pipeline
type: docker
name: default

steps:
- name: build and push container
  image: plugins/docker
  privileged: true
  settings:
    repository: git.bhaanukaul.com
    username: svc-container-manager
    password:
      from_secret: khg_bot_discord_token
    repo: git.bhaanukaul.com/bhaanukaul/khg-bot
    tags: latest
  environment:
    discord_token:
      from_secret: khg_bot_discord_token
